package com.voiceflow.mobile.p1

import com.voiceflow.mobile.generated.Attachment
import com.voiceflow.mobile.generated.ClientKind
import com.voiceflow.mobile.generated.ErrorCode
import com.voiceflow.mobile.generated.ErrorData
import com.voiceflow.mobile.generated.InitializeParams
import com.voiceflow.mobile.generated.Mark
import com.voiceflow.mobile.generated.Persona
import com.voiceflow.mobile.generated.ThreadEventUp
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The Android build is the first thing on the platform that compiles the
 * generated Kotlin contract copy, so this is where the copy is checked: it
 * matches `thread-protocol.lock`, it needs no library to exist, and the names
 * later packages rely on are the names it carries.
 *
 * A problem found here is a generation problem. It is fixed in K1's generator
 * and the file is regenerated, never patched in this copy.
 */
class GeneratedContractsTest {

    private val generated by lazy { P1Paths.file("${P1Paths.SOURCE_DIR}/generated/PlatformContracts.kt").readText() }

    private fun lockValue(key: String): String {
        val line = P1Paths.file("thread-protocol.lock").readLines()
            .firstOrNull { it.startsWith("$key=") }
            ?: throw AssertionError("thread-protocol.lock has no $key")
        return line.removePrefix("$key=").trim()
    }

    private fun headerValue(label: String): String {
        val line = generated.lineSequence()
            .firstOrNull { it.startsWith("// $label: ") }
            ?: throw AssertionError("the generated copy has no \"$label\" header line")
        return line.removePrefix("// $label: ").trim()
    }

    private fun fieldNames(type: Class<*>): Set<String> =
        type.declaredFields.filter { !it.isSynthetic }.map { it.name }.toSet()

    @Test
    fun `the protocol version is the one the platform is built on`() {
        assertEquals("thread-protocol.lock protocol_version", "2", lockValue("protocol_version"))
    }

    @Test
    fun `the copied contract file matches the lock`() {
        assertEquals("Protocol version", lockValue("protocol_version"), headerValue("Protocol version"))
        assertEquals("Schema sha256", lockValue("schema_sha256"), headerValue("Schema sha256"))
        assertEquals("Atika commit", lockValue("atika_commit"), headerValue("Atika commit"))
    }

    @Test
    fun `the generated Kotlin needs no library`() {
        val imports = generated.lineSequence().filter { it.startsWith("import ") }.toList()
        assertEquals("the just-types output imports nothing: $imports", emptyList<String>(), imports)
        for (marker in listOf("Klaxon", "klaxon", "kotlinx.serialization", "@Serializable", "com.fasterxml", "@Json")) {
            assertFalse(
                "the generated Kotlin carries $marker, so the quicktype style is not just-types",
                generated.contains(marker),
            )
        }
        assertTrue(generated.contains("package com.voiceflow.mobile.generated"))
    }

    @Test
    fun `the Swift type prefix did not leak into Kotlin`() {
        val prefixed = Regex("^(data class|enum class|class) TP[A-Z]", RegexOption.MULTILINE)
            .findAll(generated).map { it.value }.toList()
        assertEquals("Kotlin types carry no TP prefix: $prefixed", emptyList<String>(), prefixed)
    }

    @Test
    fun `the error codes the platform names exist as generated values`() {
        assertEquals("ClientNotAllowed", ErrorCode.ClientNotAllowed.name)
        val names = ErrorCode.entries.map { it.name }.toSet()
        for (code in listOf(
            "UnsupportedVersion", "InvalidParams", "NotFound", "NotSupported", "HomeUnreachable",
            "RelayTimeout", "ClientNotAllowed", "DisabledOnDevice", "KillSwitch",
            "CloudContinuationUnavailable", "RequestAlreadyResolved", "RequestExpired",
            "RuntimeUnavailable", "QuotaExceeded", "SnapshotRequired",
            "PersonaGone", "PersonaUnusable", "PersonaIsDefault", "PersonaInUse",
            "NameTaken", "InvalidPersona", "TemplateUnknown",
        )) {
            assertTrue("ErrorCode.$code is missing: $names", names.contains(code))
        }
        assertFalse("there is no revision_conflict code", names.contains("RevisionConflict"))
    }

    @Test
    fun `the phone is a client kind the contract knows`() {
        assertEquals("Android", ClientKind.Android.name)
        assertEquals(setOf("Android", "Browser", "MAC", "Trigger"), ClientKind.entries.map { it.name }.toSet())
    }

    @Test
    fun `the record shapes later packages read carry the fields they read`() {
        assertTrue(fieldNames(ErrorData::class.java).containsAll(setOf("code", "message", "retryable")))
        assertTrue(fieldNames(InitializeParams::class.java).containsAll(setOf("client", "protocolVersion")))
        assertTrue(fieldNames(ThreadEventUp::class.java).containsAll(setOf("at", "event")))
        assertTrue(
            fieldNames(Attachment::class.java)
                .containsAll(setOf("id", "kind", "mime", "name", "sha256", "sizeBytes", "forModel")),
        )
        assertTrue(fieldNames(Persona::class.java).containsAll(setOf("id", "name", "coreMemory", "revision", "isDefault")))
        assertTrue(fieldNames(Mark::class.java).containsAll(setOf("box", "color", "kind", "n")))
    }
}
