#!/bin/bash
# Tests scripts/sync-thread-protocol.sh against a throwaway stand-in for the Atika repository.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT="$REPO_ROOT/scripts/sync-thread-protocol.sh"
WORK="$(mktemp -d /tmp/vf-thread-protocol-test.XXXXXX)"
trap 'rm -rf "$WORK"' EXIT
PASS=0

ok() { PASS=$((PASS + 1)); echo "ok $PASS - $1"; }
die() { echo "not ok - $1" >&2; exit 1; }

# A stand-in Atika repository with two commits of generated files.
ATIKA="$WORK/atika"
SRC="$ATIKA/packages/thread-protocol"
OTHER="$ATIKA/packages/home-contract"
mkdir -p "$SRC/generated/swift" "$SRC/generated/kotlin" "$SRC/fixtures/rules" "$OTHER/fixtures"
git -C "$WORK" init -q atika
# The real generated files are thousands of lines long, so the stand-ins are
# longer than any `head` window a reader of the header might use: a stage that
# closes the pipe early would take SIGPIPE here and fail the test.
write_generated() { # <hash>
    for file in generated/swift/PlatformContracts.swift generated/swift/PlatformContractsFixtures.swift generated/kotlin/PlatformContracts.kt; do
        {
            printf '// Generated by packages/thread-protocol/scripts/generate.ts. Do not edit.\n'
            printf '// Contract set: platform-contracts\n'
            printf '// Protocol version: 2\n'
            printf '// Schema sha256: %s\n' "$1"
            printf '// Contract versions: thread-protocol 2, home-contract 1\n\n'
            printf 'body of %s\n' "$file"
            seq 1 5000 | sed 's|^|// filler line |'
        } > "$SRC/$file"
    done
    # The fixture table names the fixtures folder of every contract set; the script copies each of them.
    {
        printf 'let tpFixtureFolders: [(contractSet: String, folder: String)] = [\n'
        printf '    (contractSet: "thread-protocol", folder: "packages/thread-protocol/fixtures"),\n'
        printf '    (contractSet: "home-contract", folder: "packages/home-contract/fixtures"),\n'
        printf ']\n'
    } >> "$SRC/generated/swift/PlatformContractsFixtures.swift"
    echo '{"type":"Thread","examples":[]}' > "$SRC/fixtures/Thread.json"
    echo '{"type":"FileEntry","examples":[]}' > "$OTHER/fixtures/FileEntry.json"
    echo '{"rule":"threadBranchName","cases":[]}' > "$SRC/fixtures/rules/branch-names.json"
}
commit_atika() {
    git -C "$ATIKA" add -A
    git -C "$ATIKA" -c user.name=test -c user.email=test@example.com commit -q -m "$1"
    git -C "$ATIKA" rev-parse HEAD
}
write_generated aaaa1111
FIRST="$(commit_atika first)"
write_generated bbbb2222
SECOND="$(commit_atika second)"

VF="$WORK/voice-flow"
mkdir -p "$VF"
run() { ATIKA_REPO="$ATIKA" VF_PROJECT_DIR="$VF" "$SCRIPT" "$@"; }

run --check >/dev/null 2>&1 && die "--check must fail when there is no lock file"
ok "--check fails without a lock file"

run --update "$FIRST" >/dev/null
grep -q "^atika_commit=$FIRST$" "$VF/thread-protocol.lock" || die "lock names the commit"
grep -q "^protocol_version=2$" "$VF/thread-protocol.lock" || die "lock names the protocol version"
grep -q "^schema_sha256=aaaa1111$" "$VF/thread-protocol.lock" || die "lock names the schema hash"
ok "--update writes the lock from the commit's header"

SWIFT="$VF/swift/Generated/PlatformContracts.swift"
[ "$(sed -n 5p "$SWIFT")" = "// Atika commit: $FIRST" ] || die "the commit line sits beneath the schema hash"
[ "$(sed -n 6p "$SWIFT")" = "// Contract versions: thread-protocol 2, home-contract 1" ] || die "the contract versions line is kept"
grep -q "body of generated/swift/PlatformContracts.swift" "$SWIFT" || die "the body is copied"
[ -f "$VF/swift/Generated/PlatformContractsFixtures.swift" ] || die "the fixture table is copied"
[ -f "$VF/android/app/src/main/kotlin/com/voiceflow/mobile/generated/PlatformContracts.kt" ] || die "Kotlin is copied"
[ -f "$VF/contract-fixtures/thread-protocol/Thread.json" ] || die "fixtures are copied"
[ -f "$VF/contract-fixtures/thread-protocol/rules/branch-names.json" ] || die "rule fixtures are copied"
[ -f "$VF/contract-fixtures/home-contract/FileEntry.json" ] || die "the fixtures of every contract set named in the fixture table are copied"
[ -z "$(find "$VF/swift/Generated" -type f ! -name '*.swift' -print -quit)" ] || die "swift/Generated holds nothing but Swift files, because it is inside the build target"
ok "Swift lands in swift/Generated, Kotlin in the Android source tree, fixtures in contract-fixtures"

run --check >/dev/null || die "--check passes after a sync"
ok "--check passes after a sync"

sed -i.bak 's|^// Schema sha256: .*|// Schema sha256: tampered|' "$SWIFT" && rm -f "$SWIFT.bak"
run --check >/dev/null 2>&1 && die "--check must fail when a header does not match the lock"
ok "--check fails when a header does not match the lock"

run >/dev/null
run --check >/dev/null || die "a plain run restores the pinned files"
ok "a plain run copies again from the pinned commit"

touch "$VF/contract-fixtures/thread-protocol/Stale.json"
mkdir -p "$VF/contract-fixtures/retired-contract" && touch "$VF/contract-fixtures/retired-contract/Old.json"
touch "$VF/swift/Generated/ThreadProtocol.swift"
run --update "$SECOND" >/dev/null
grep -q "^schema_sha256=bbbb2222$" "$VF/thread-protocol.lock" || die "lock moves to the new hash"
[ ! -f "$VF/contract-fixtures/thread-protocol/Stale.json" ] || die "stale fixtures are removed"
[ ! -d "$VF/contract-fixtures/retired-contract" ] || die "the fixtures of a contract set that is gone are removed"
[ ! -f "$VF/swift/Generated/ThreadProtocol.swift" ] || die "a generated file from before the combined output is removed"
ok "--update moves to a new commit and removes stale fixtures"

sed -i.bak "s|^schema_sha256=.*|schema_sha256=wrong|" "$VF/thread-protocol.lock" && rm -f "$VF/thread-protocol.lock.bak"
run >/dev/null 2>&1 && die "a plain run must refuse a lock that disagrees with its commit"
ok "a plain run refuses a lock that disagrees with its commit"

run --update not-a-commit >/dev/null 2>&1 && die "--update must refuse an unknown commit"
ok "--update refuses an unknown commit"

# Ruling 4, first half: --check verifies every copied file, not only the three
# headers. The lock carries one sha256 line per copied file.
run --update "$SECOND" >/dev/null
grep -q '^sha256 [0-9a-f]\{64\} contract-fixtures/thread-protocol/Thread.json$' "$VF/thread-protocol.lock" ||
    die "the lock records one sha256 line per copied file"
# A file the Finder leaves behind is not a copied file. `.gitignore` hides
# `.DS_Store` from `git status`, so if it were counted, `--check` would fail on
# a tree that is in fact correct, and install.sh — which runs `--check` before
# every build — would refuse to build until the Atika clone was at hand again.
touch "$VF/contract-fixtures/thread-protocol/.DS_Store"
run --check >/dev/null 2>&1 || die "a dot-file under contract-fixtures must not break --check"
rm -f "$VF/contract-fixtures/thread-protocol/.DS_Store"
ok "a dot-file the Finder leaves behind is not counted as a copied file"

printf 'x' >> "$VF/contract-fixtures/thread-protocol/Thread.json"
MESSAGE="$(run --check 2>&1)" && die "--check must fail when a copied file changed"
case "$MESSAGE" in
    *"contract-fixtures/thread-protocol/Thread.json"*) ;;
    *) die "--check names the file that differs; it said: $MESSAGE" ;;
esac
ok "--check recomputes every copied file and names the one that differs"

# Ruling 4, second half: the lock is written last, so a run that dies during the
# copy leaves the lock that was there before. A third commit whose fixture table
# names a contract set that has no folder in that commit makes `git archive`
# fail in the middle of the copy, with no test-only hook in the script.
write_generated cccc3333
printf '    (contractSet: "vanished-contract", folder: "packages/vanished-contract/fixtures"),\n' \
    >> "$SRC/generated/swift/PlatformContractsFixtures.swift"
THIRD="$(commit_atika third)"
LOCK_BEFORE="$(cat "$VF/thread-protocol.lock")"
run --update "$THIRD" >/dev/null 2>&1 && die "--update must fail when a named fixtures folder is not in the commit"
[ "$(cat "$VF/thread-protocol.lock")" = "$LOCK_BEFORE" ] ||
    die "an interrupted run leaves the lock that was there before, not one describing files that are not there"
run --check >/dev/null 2>&1 && die "--check must report the half-copied tree the interrupted run left"
ok "the lock is written last, and --check reports the tree an interrupted run left"

# Ruling 4 names the mechanism as well as the outcome: the lock is "written
# last, to a temporary file in the same directory, and renamed into place". The
# check above cannot see the mechanism — a write_lock that wrote straight to the
# lock would also leave the old lock behind when the run died during the copy —
# so the shape of the function is read here, and the reading is proved able to
# go red against a copy of the script that writes straight to the lock.
write_lock_renames() { # <script>
    /usr/bin/awk '
        /^write_lock\(\)/ { inside = 1; next }
        inside && /^\}$/ { inside = 0 }
        inside && /> *"\$temporary"/ { temporary = 1 }
        inside && /mv "\$temporary" "\$LOCK"/ { renamed = 1 }
        inside && /> *"\$LOCK"/ { direct = 1 }
        END { exit (temporary && renamed && !direct) ? 0 : 1 }
    ' "$1"
}
write_lock_renames "$SCRIPT" ||
    die "write_lock writes the lock to a temporary file and renames it into place"
MUTANT="$WORK/writes-straight-to-the-lock.sh"
sed -e 's|} > "$temporary"|} > "$LOCK"|' -e '/mv "$temporary" "$LOCK"/d' "$SCRIPT" > "$MUTANT"
write_lock_renames "$MUTANT" &&
    die "the reading must go red on a write_lock that writes straight to the lock"
ok "write_lock writes a temporary file and renames it, and the reading sees when it does not"

[ -z "$(find "$VF" -maxdepth 1 -name 'thread-protocol.lock.writing.*' -print -quit)" ] ||
    die "no temporary lock file survives a run"
ok "no temporary lock file is left behind"

echo "all $PASS checks passed"
