#!/bin/bash
# Tests scripts/sync-thread-protocol.sh against a throwaway stand-in for the Atika repository.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT="$REPO_ROOT/scripts/sync-thread-protocol.sh"
WORK="$(mktemp -d /tmp/vf-thread-protocol-test.XXXXXX)"
trap 'rm -rf "$WORK"' EXIT
PASS=0

ok() { PASS=$((PASS + 1)); echo "ok $PASS - $1"; }
die() { echo "not ok - $1" >&2; exit 1; }

# A stand-in Atika repository with two commits of generated files.
ATIKA="$WORK/atika"
SRC="$ATIKA/packages/thread-protocol"
OTHER="$ATIKA/packages/home-contract"
mkdir -p "$SRC/generated/swift" "$SRC/generated/kotlin" "$SRC/fixtures/rules" "$OTHER/fixtures"
git -C "$WORK" init -q atika
# The real generated files are thousands of lines long, so the stand-ins are
# longer than any `head` window a reader of the header might use: a stage that
# closes the pipe early would take SIGPIPE here and fail the test.
write_generated() { # <hash>
    for file in generated/swift/PlatformContracts.swift generated/swift/PlatformContractsFixtures.swift generated/kotlin/PlatformContracts.kt; do
        {
            printf '// Generated by packages/thread-protocol/scripts/generate.ts. Do not edit.\n'
            printf '// Contract set: platform-contracts\n'
            printf '// Protocol version: 2\n'
            printf '// Schema sha256: %s\n' "$1"
            printf '// Contract versions: thread-protocol 2, home-contract 1\n\n'
            printf 'body of %s\n' "$file"
            seq 1 5000 | sed 's|^|// filler line |'
        } > "$SRC/$file"
    done
    # The fixture table names the fixtures folder of every contract set; the script copies each of them.
    {
        printf 'let tpFixtureFolders: [(contractSet: String, folder: String)] = [\n'
        printf '    (contractSet: "thread-protocol", folder: "packages/thread-protocol/fixtures"),\n'
        printf '    (contractSet: "home-contract", folder: "packages/home-contract/fixtures"),\n'
        printf ']\n'
    } >> "$SRC/generated/swift/PlatformContractsFixtures.swift"
    echo '{"type":"Thread","examples":[]}' > "$SRC/fixtures/Thread.json"
    echo '{"type":"FileEntry","examples":[]}' > "$OTHER/fixtures/FileEntry.json"
    echo '{"rule":"threadBranchName","cases":[]}' > "$SRC/fixtures/rules/branch-names.json"
}
commit_atika() {
    git -C "$ATIKA" add -A
    git -C "$ATIKA" -c user.name=test -c user.email=test@example.com commit -q -m "$1"
    git -C "$ATIKA" rev-parse HEAD
}
write_generated aaaa1111
FIRST="$(commit_atika first)"
write_generated bbbb2222
SECOND="$(commit_atika second)"

VF="$WORK/voice-flow"
mkdir -p "$VF"
run() { ATIKA_REPO="$ATIKA" VF_PROJECT_DIR="$VF" "$SCRIPT" "$@"; }

run --check >/dev/null 2>&1 && die "--check must fail when there is no lock file"
ok "--check fails without a lock file"

run --update "$FIRST" >/dev/null
grep -q "^atika_commit=$FIRST$" "$VF/thread-protocol.lock" || die "lock names the commit"
grep -q "^protocol_version=2$" "$VF/thread-protocol.lock" || die "lock names the protocol version"
grep -q "^schema_sha256=aaaa1111$" "$VF/thread-protocol.lock" || die "lock names the schema hash"
ok "--update writes the lock from the commit's header"

SWIFT="$VF/swift/Generated/PlatformContracts.swift"
[ "$(sed -n 5p "$SWIFT")" = "// Atika commit: $FIRST" ] || die "the commit line sits beneath the schema hash"
[ "$(sed -n 6p "$SWIFT")" = "// Contract versions: thread-protocol 2, home-contract 1" ] || die "the contract versions line is kept"
grep -q "body of generated/swift/PlatformContracts.swift" "$SWIFT" || die "the body is copied"
[ -f "$VF/swift/Generated/PlatformContractsFixtures.swift" ] || die "the fixture table is copied"
[ -f "$VF/android/app/src/main/kotlin/com/voiceflow/mobile/generated/PlatformContracts.kt" ] || die "Kotlin is copied"
[ -f "$VF/swift/Generated/thread-protocol-fixtures/Thread.json" ] || die "fixtures are copied"
[ -f "$VF/swift/Generated/thread-protocol-fixtures/rules/branch-names.json" ] || die "rule fixtures are copied"
[ -f "$VF/swift/Generated/home-contract-fixtures/FileEntry.json" ] || die "the fixtures of every contract set named in the fixture table are copied"
ok "files land in swift/Generated, the Android source tree and the fixtures folder"

run --check >/dev/null || die "--check passes after a sync"
ok "--check passes after a sync"

sed -i.bak 's|^// Schema sha256: .*|// Schema sha256: tampered|' "$SWIFT" && rm -f "$SWIFT.bak"
run --check >/dev/null 2>&1 && die "--check must fail when a header does not match the lock"
ok "--check fails when a header does not match the lock"

run >/dev/null
run --check >/dev/null || die "a plain run restores the pinned files"
ok "a plain run copies again from the pinned commit"

touch "$VF/swift/Generated/thread-protocol-fixtures/Stale.json"
mkdir -p "$VF/swift/Generated/retired-contract-fixtures" && touch "$VF/swift/Generated/retired-contract-fixtures/Old.json"
touch "$VF/swift/Generated/ThreadProtocol.swift"
run --update "$SECOND" >/dev/null
grep -q "^schema_sha256=bbbb2222$" "$VF/thread-protocol.lock" || die "lock moves to the new hash"
[ ! -f "$VF/swift/Generated/thread-protocol-fixtures/Stale.json" ] || die "stale fixtures are removed"
[ ! -d "$VF/swift/Generated/retired-contract-fixtures" ] || die "the fixtures folder of a contract set that is gone is removed"
[ ! -f "$VF/swift/Generated/ThreadProtocol.swift" ] || die "a generated file from before the combined output is removed"
ok "--update moves to a new commit and removes stale fixtures"

sed -i.bak "s|^schema_sha256=.*|schema_sha256=wrong|" "$VF/thread-protocol.lock" && rm -f "$VF/thread-protocol.lock.bak"
run >/dev/null 2>&1 && die "a plain run must refuse a lock that disagrees with its commit"
ok "a plain run refuses a lock that disagrees with its commit"

run --update not-a-commit >/dev/null 2>&1 && die "--update must refuse an unknown commit"
ok "--update refuses an unknown commit"

echo "all $PASS checks passed"
